--- 
apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    app: httpd
    appversion: 1.0.1
    env: PROD
spec:
  containers:
  - name: httpd
    image: httpd 
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
      requests:
        memory: "64Mi"
        cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    app: httpd
    appversion: 1.0.1
    env: PROD
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  type: NodePort
  ports:
    - port: 3036
      nodePort: 30036
      name: http
  selector:
    name: mysql