apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: httpd
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
      app: httpd
  template:
    metadata:
      labels:
        tier: frontend
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          requests:
            memory: "64Mi"
            cpu: "250m"