---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-x1
  annotations:
    proj: x*
spec:
  containers:
  - name: httpd
    image: httpd
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
    ports:
      - containerPort: 80