## For using node selector you need to setup some labels to the nodes.
## kubectl label nodes <node-name> <label-key>=<label-value>
## kubectl label nodes gke-standard-cluster-1-default-pool-1d9a836a-9nwg STORAGE=true --overwrite
---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-x1
spec:
  containers:
  - name: httpd
    image: httpd
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
    ports:
      - containerPort: 80