## For using node selector you need to setup some labels to the nodes.
## kubectl label nodes <node-name> <label-key>=<label-value>

---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-x1
  annotations:
    proj: x*
spec:
  containers:
  - name: httpd
    image: httpd
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
    ports:
      - containerPort: 80