---
apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: STORAGE
            operator: In
            values:
            - "true"
            - "yes"
  containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0

#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: with-node-affinity-required
#spec:
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingRequiredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: STORAGE
#            operator: In
#            values:
#            - "true"
#            - "yes"
#  containers:
#  - name: with-node-affinity-req
#    image: k8s.gcr.io/pause:2.0
