---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pa
  labels:
    app: httpd
spec:
  containers:
  - name: myapp
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80

--- 
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - httpd
        topologyKey: "kubernetes.io/hostname"
  containers:
  - name: with-pod-affinity
    image: k8s.gcr.io/pause:2.0

--- 
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-anti-affinity
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - httpd
          topologyKey: "kubernetes.io/hostname"
  containers:
  - name: with-pod-anti-affinity
    image: k8s.gcr.io/pause:2.0