## Taints should be applied on Nodes
## Tolerations should be given to Pods

---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-non-tolerated
  labels:
    name: httpd
spec:
  containers:
  - name: httpd
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80

--- 
apiVersion: v1
kind: Pod
metadata:
  name: httpd-tolerated
  labels:
    name: httpd
spec:
  tolerations:
- key: "key1"
  operator: "Equal"
  value: "value1"
  effect: "NoExecute"
  containers:
  - name: httpd
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80