## Taints should be applied on Nodes
## Tolerations should be given to Pods

apiVersion: v1
kind: Pod
metadata:
  name: httpd-non-tolerated
  labels:
    name: httpd
spec:
  containers:
  - name: httpd
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
