apiVersion: v1
kind: Pod
metadata:
  name: httpd-env
  labels:
    name: httpd
spec:
  containers:
  - name: myapp
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: <Port>
