apiVersion: v1
kind: Pod
metadata:
  name: httpd-env
  labels:
    name: httpd
spec:
  containers:
  - name: myapp
    image: httpd
    env:
      - name: PROJECT_
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
