apiVersion: v1
kind: Pod
metadata:
  name: httpd-readiness
  labels:
    name: httpd
spec:
  containers:
  - name: httpd
    image: httpd
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
