apiVersion: v1
kind: Pod
metadata:
  name: httpd-readiness
  labels:
    name: httpd
spec:
  containers:
  - name: httpd
    image: httpd
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
