--- 
apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  serviceAccountName: admin
  containers:
  - name: debug
    image: centos 
    command: ["sleep", "10000"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "250m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    