---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: httpd-data 
data:
  course_name: Kubernetes
  course_time: 12pm
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-httpd-cm 
spec:
  containers:
    - name: httpd 
      image: httpd
      resources:
        limits:
          memory: "64Mi"
          cpu: "50m"
      env:
        - name: COURSE_NAME
          valueFrom:
            configMapKeyRef:
              name: httpd-data
              key: course_name 

