---
apiVersion: v1
kind: Pod 
metadata: 
  name: httpd-data 
data:
  course_name: DevOps
  course_time: 8pm
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-httpd-cm 
spec:
  containers:
    - name: httpd 
      image: rkalluru/httpd-cm:v1
      resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
      env:
        - name: COURSE_NAME
          valueFrom:
            configMapKeyRef:
              name: httpd-data
              key: COURSE_NAME 
