apiVersion: v1
kind: Pod
metadata:
  name: centos-httpd-cm 
spec:
  containers:
    - name: httpd 
      image: rkalluru/httpd-cm:v1
      env:
        - name: COURSE_NAME
          valueFrom:
            configMapKeyRef:
              name: config-1
              key: PROJECT_ENV