apiVersion: v1
kind: Pod
metadata:
  name: sample
  labels:
    name: web
spec:
  containers:
  - name: sample
    image: rkalluru/sec-context:v3
  securityContext:
    runAsUser: 10000
    runAsGroup: 30000
    supplementalGroups:
      - 30000
