apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo
spec:
  containers:
    - name: demo
      image: centos
      command: ["sleep", "30000"]
  securityContext:
    runAsUser: 10000
    runAsGroup: 30000
