---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---     
apiVersion: v1
kind: Pod
metadata:
  name: sample-1
spec:
  containers:
  - name: sample
    image: centos 
    command: ["sleep", "30000"]
    volumeMounts:
      - mountPath: "/opt/data"
        name: demo1
  volumes:
    - name: demo1
      persistentVolumeClaim:
        claimName: demo1
  initContainers:
  - name: init-myservice
    image: centos
    command: ["touch", "/opt/data/demo"]
    volumeMounts:
      - mountPath: "/opt/data"
        name: demo1


