---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi

---     
apiVersion: v1
kind: Pod
metadata:
  name: sample-1
spec:
  containers:
  - name: sample
    image: centos 
    command: ["sleep", "30000"]
  initContainers:
  - name: init-myservice
    image: centos
    command: ["touch", "/opt/demo"]


