--- 
apiVersion: v1
kind: Secret
metadata:
  name: demo1
type: Opaque
data:
  COURSE_NAME: RGV2T3Bz

--- 
apiVersion: v1
kind: Pod
metadata:
  name: centos-httpd-secret1
spec:
  containers:
    - name: httpd 
      image: centos
      command: ["sleep", "10000"]
      resources:
        limits:
          memory: "64Mi"
          cpu: "50m"
      env:
        - name: COURSE_NAME
          valueFrom:
            secretKeyRef:
              name: demo1
              key: COURSE_NAME 