--- 
apiVersion: v1
kind: Secret
metadata:
  name: demo1
type: Opaque
data:
  COURSE_NAME: RGV2T3Bz

--- 
apiVersion: v1
kind: Pod
metadata:
  name: centos-httpd-secret1
spec:
  containers:
    - name: httpd 
      image: rkalluru/httpd-:v1
      resources:
        limits:
          memory: "64Mi"
          cpu: "50m"
      env:
        - name: COURSE_NAME
          valueFrom:
            configMapKeyRef:
              name: httpd-data
              key: course_name 