nexus.devopsproj.com/httpd-cm:v1

--- 
apiVersion: v1
kind: Pod
metadata:
  name: centos-httpd-secret1
spec:
  containers:
    - name: httpd 
      image: nexus.devopsproj.com/httpd-cm:v1
      command: ["sleep", "10000"]
      resources:
        limits:
          memory: "64Mi"
          cpu: "50m"
