--- 
apiVersion: v1
kind: Pod
metadata:
  name: image-secret
spec:
  containers:
    - name: httpd 
      image: nexus.devopsproj.com/httpd-cm:v1
      resources:
        limits:
          memory: "64Mi"
          cpu: "50m"
