apiVersion: v1
kind: Pod
metadata: 
 name: webserver
 labels:
  env: prod
spec:
 containers:
  - name: nginx
    image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: prod
spec:
  type: LoadBalancer
  selector:
    env: prod
  ports:
    - protocol: TCP
      port: 80
  
