apiVersion: v1
kind: Pod
metadata: 
 name: http
 labels:
  env: prod1
spec:
 containers:
  - name: http
    image: httpd

---
apiVersion: v1
kind: Service
metadata:
  name: prod1
spec:
  type: NodePort 
  selector:
    env: prod1
  ports:
    - protocol: TCP
      port: 80
  
